# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Admin.create!( email: "test@test.com", password: "test1234", password_confirmation: "test1234")
Admin.create!( email: "tests@tests.com", password: "tests1234", password_confirmation: "tests1234")
# Customer.create!( email: "test@test1.com", password: "test1234", password_confirmation: "test1234")
# Customer.create!( email: "test@test2.com", password: "test1234", password_confirmation: "test1234")
# Customer.create!( email: "test@test3.com", password: "test1234", password_confirmation: "test1234")
# Customer.create!( email: "test@test4.com", password: "test1234", password_confirmation: "test1234")
# Customer.create!( email: "test@test5.com", password: "test1234", password_confirmation: "test1234")
# Customer.create!( email: "test@test6.com", password: "test1234", password_confirmation: "test1234")
# Customer.create!( email: "test@test7.com", password: "test1234", password_confirmation: "test1234")
# Customer.create!( email: "test@test8.com", password: "test1234", password_confirmation: "test1234")
# Customer.create!( email: "test@test9.com", password: "test1234", password_confirmation: "test1234")
# Customer.create!( email: "test@test10.com", password: "test1234", password_confirmation: "test1234")
# Customer.create!( email: "test@test11.com", password: "test1234", password_confirmation: "test1234")
# Customer.create!( email: "test@test12.com", password: "test1234", password_confirmation: "test1234")
# Customer.create!( email: "test@test13.com", password: "test1234", password_confirmation: "test1234")
# Customer.create!( email: "test@test14.com", password: "test1234", password_confirmation: "test1234")
# Customer.create!( email: "test@test15.com", password: "test1234", password_confirmation: "test1234")
# Customer.create!( email: "test@test16.com", password: "test1234", password_confirmation: "test1234")
# Customer.create!( email: "test@test17.com", password: "test1234", password_confirmation: "test1234")
# Customer.create!( email: "test@test18.com", password: "test1234", password_confirmation: "test1234")
# Customer.create!( email: "test@test19.com", password: "test1234", password_confirmation: "test1234")
# Customer.create!( email: "test@test20.com", password: "test1234", password_confirmation: "test1234")
# Customer.create!( email: "test@test21.com", password: "test1234", password_confirmation: "test1234")
# Customer.create!( email: "test@test22.com", password: "test1234", password_confirmation: "test1234")
# Customer.create!( email: "test@test23.com", password: "test1234", password_confirmation: "test1234")
# Customer.create!( email: "test@test24.com", password: "test1234", password_confirmation: "test1234")
# Customer.create!( email: "test@test25.com", password: "test1234", password_confirmation: "test1234")
